swagger: '2.0'
info:
  title: Falling Fruit API
  description: The Falling Fruit API provides access to the Falling Fruit database.
  version: 0.2.0
host: 'localhost:3100'
basePath: /api/0.2
tags:
  - name: clusters
    description: Clusters summarize the count and center of mass of Locations available in an area. They are computed on a nested [quadtree](https://en.wikipedia.org/wiki/Quadtree) which, at a given `zoom` level, divides the Earth into a 2<sup>zoom</sup> x 2<sup>zoom</sup> grid of equal-sized squares.
schemes:
  - http
paths:
  /clusters.json:
    get:
      tags:
        - clusters
      summary: List clusters
      produces:
        - application/json
      parameters:
        - name: swlng
          description: Longitude of southwest corner in WGS84 decimal degrees.
          in: query
          type: number
          required: true
        - name: nelng
          description: Longitude of northeast corner in WGS84 decimal degrees.
          in: query
          type: number
          required: true
        - name: swlat
          description: Latitude of southwest corner in WGS84 decimal degrees.
          in: query
          type: number
          required: true
        - name: nelat
          description: Latitude of northeast corner in WGS84 decimal degrees.
          in: query
          type: number
          required: true
        - name: zoom
          description: 'Zoom level, where the world is divided into a 2^zoom x 2^zoom grid.'
          in: query
          required: false
          type: integer
          minimum: 0
          maximum: 12
          default: 0
        - name: muni
          description: >-
            Whether to count Types at Locations imported from municipal tree
            inventories.
          in: query
          required: false
          type: boolean
          default: true
        - name: types
          description: IDs of Types to count (or all if empty or missing).
          in: query
          required: false
          type: array
          items:
            type: integer
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/Cluster'
      security:
        - api_key: []
securityDefinitions:
  api_key:
    type: apiKey
    name: api_key
    in: query
definitions:
  Cluster:
    title: Cluster
    description: Clusters summarize the number of Location Types available in an area.
    type: object
    properties:
      lng:
        description: >-
          Longitude (in WGS84 decimal degrees) of the centerpoint of all
          included Location Types.
        type: number
        example: -123.45678
      lat:
        description: >-
          Latitude (in WGS84 decimal degrees) of the centerpoint of all included
          Location Types.
        type: number
        example: 45.67890
      count:
        type: integer
        description: Number of Location Types.
        example: 768
